name: Test Workflow

on:
  pull_request:

jobs:
  job-1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - x: 1
            y: 2
          - x: 3
            y: 4
    env:
      BOX_TYPE: cozy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: command test
        run: |
          echo $BOX_TYPE
          echo ${{ env.BOX_TYPE }}
          echo ${{ matrix.x }}
          echo ${{ matrix.y }}
