name: Test Workflow

on:
  pull_request:
  workflow_dispatch:
    inputs:
      test-case:
        description: 'Test Cases To Run'
        required: true
        default: all

env:
  GLOBAL_VAR: 7

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install jq

      - name: Setup matrix combinations
        id: set-matrix
        run: |
          INPUT_TEST_CASE=${{ github.event.inputs.test-case }}
          echo $INPUT_TEST_CASE

          MATRIX_TEST_CASE=$(jq -c --null-input --arg test_case $INPUT_TEST_CASE \
          '[
            $test_case
          ]')
          
          
          MATRIX_TEST_CASE_ALL=$(jq -c --null-input \
          '[
            "case-1",
            "case-2"
          ]')

          echo $MATRIX_TEST_CASE_ALL

          if [[ $INPUT_TEST_CASE == "all" || $INPUT_TEST_CASE == "" ]]; then
            echo "::set-output name=matrix::$MATRIX_TEST_CASE_ALL"
          else
            echo "::set-output name=matrix::$MATRIX_TEST_CASE"
          fi

  job-1:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix:
        test-case: ${{ fromJSON(needs.setup-matrix.outputs.matrix) }}
    env:
      BOX_TYPE: cozy
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      - name: Set Output
        id: step-1
        run: |
          echo "${{ toJSON(needs.setup-matrix.outputs.matrix) }}"
          if [[ ${{ matrix.test-case }} == "case-1" ]]; then
            EMU=$(echo -e "abc\nxyz")
            for i in $EMU; do
              echo $i
            done

            exit 0
          else
            exit 0
          fi
      - name: Check Status of step-1
        if: always()
        run: |
          echo "step-1 Status: ${{ steps.step-1.outcome }}"

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: always()
    steps:
      - name: command test
        run: |
          echo $BOX_TYPE
          echo ${{ env.BOX_TYPE }}
          echo ${{ matrix.x }}
          echo ${{ matrix.y }}
          echo ${{ env.GLOBAL_VAR }}
          echo ${{ needs.job-1.result }}
          pwd
          ls -al