name: Test Workflow

on:
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: 'Test Cases To Run'
        required: true
        default: all

env:
  GLOBAL_VAR: 7

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
      - name: Setup matrix combinations
        run: |
          if [[ ${{ github.event.inputs.name }} == "all" ]]; then
            echo "::set-output name=matrix::[\"case-1\",\"case-2\"]"
          fi
      
  job-1:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix:
        test-case: ${{ fromJSON(needs.setup-matrix.outputs.matrix) }}
    env:
      BOX_TYPE: cozy
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      - name: Set Output
        id: step-1
        run: |
          if [[ ${{ matrix.test-case }} == "case-1" ]]; then
            EMU=$(echo -e "abc\nxyz")
            for i in $EMU; do
              echo $i
            done

            exit 0
          else
            exit 0
          fi
      - name: Check Status of step-1
        if: always()
        run: |
          echo "step-1 Status: ${{ steps.step-1.outcome }}"

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: always()
    steps:
      - name: command test
        run: |
          echo $BOX_TYPE
          echo ${{ env.BOX_TYPE }}
          echo ${{ matrix.x }}
          echo ${{ matrix.y }}
          echo ${{ env.GLOBAL_VAR }}
          echo ${{ needs.job-1.result }}
          pwd
          ls -al